### ISSUE TITLE
Private Messages can still be reported

### ISSUE THREAD

**Issue by Timongcraft** [Blayung/liberated-chat#1]
Hello,
this is a nice plugin and very simple but with chat reporting you can also report private messages like /msg, /tell and /w.
So it would be nice if you add a msg command you can just override the msg command with a bukkit command but then you can still report messages from minecraft:msg etc. you could block those commands or use something like the [CommandAPI](https://commandapi.jorel.dev) to create a msg command and unregister the normal command.
E.g. for such a command: https://gist.github.com/Timongcraft/5649c36b4d290eaed0bfe01240bddac0

Edit: The example makes it also so you can't have a selector with more than one player

**Comment by Blayung** [comment]
Bro I can't belive this plugin is so popular to recieve an issue xD
I didn't know that you can report private messages, I'll try to fix it soon. Thanks for the feedback.

EDIT: I think I'll finish doing it today.

**Comment by Blayung** [comment]
@Timongcraft Hey, I've seen you are also developing minecraft mods/plugins. I encountered a shitty problem, wanna help me? I put my code on the dev branch. I can give you my discord if you are willing to help 😃

**Comment by Timongcraft** [comment]
@Blayung discord would be nice mine is Timongcraft#5454 and i would love to help you.

**Comment by Blayung** [comment]
I've sent you an invite
